# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  #Python deps (pip / Poetry / pyproject.toml)
  - package-ecosystem: "pip"
    directory: "/"              # path containing requirements*.txt or pyproject.toml
    schedule:
      interval: "daily"        # daily | weekly | monthly
      time: "09:00"
      timezone: "Asia/Singapore"
    allow:
      - dependency-type: "all"  # direct + indirect
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
    rebase-strategy: "disabled" # or "auto"
    groups:
      prod-deps:
        applies-to: security-updates
        patterns:
          - "*"
      dev-toolkits:
        applies-to: version-updates
        patterns:
          - "black"
          - "ruff*"
          - "mypy*"
          - "pytest*"

