import logging
from typing import Dict, Any, Annotated
import operator
from langchain_core.messages import BaseMessage

logger = logging.getLogger(__name__)

class GraphState(Dict[str, Any]):
    """
    Represents the state of the LangGraph.

    Attributes:
        messages (list[BaseMessage]): A list of messages in the conversation history.
        guardrails_output (str, optional): Output from guardrails, if any.
        final_response (str, optional): The final response generated by the graph.
        node_outputs (Dict[str, Any]): A dictionary to store outputs from different nodes.
    """
    messages: list[BaseMessage]
    guardrails_output: str = None
    final_response: str = None
    node_outputs: Annotated[Dict[str, Any], operator.or_] = {}
